-- Clear all data from tables (keep schema and RLS)
truncate table public.feedback_submissions;
truncate table public.feedback_categories;
truncate table public.feedback_subjects;
truncate table public.canteen_menu;
truncate table public.available_books;
truncate table public.issued_books;
truncate table public.payment_history;
truncate table public.fee_structure;
truncate table public.previous_semesters;
truncate table public.semester_marks;
truncate table public.attendance_records;
truncate table public.attendance_by_subject;
truncate table public.calendar_events;
truncate table public.todays_classes;
truncate table public.upcoming_events;
truncate table public.timetable;
truncate table public.notices;
truncate table public.student_achievements;
truncate table public.student_skills;
truncate table public.academic_info;
truncate table public.student_profile cascade;
